// The printable 600x900mm site board ("Notice about building work") - the HazardCo board,
// rebuilt in-house. Rendered with @react-pdf/renderer at true print size so the print shop
// gets a 1:1 PDF: 600x900mm = [1700.79, 2551.18] points (1pt = 1/72", 1mm = 2.8346pt).
//
// EVERY information line is a fillable AcroForm field (TextInput / Checkbox), pre-filled with
// whatever the app knows - Chris populates/adjusts the rest directly in Adobe Acrobat before
// sending to print. Layout fills the full sheet (v1 left a third of the page empty) and
// hyphenation is disabled (v1 printed "RE-QUIRED").
//
// Server-only (imported by the board-pdf route). The QR png (data URL) is generated by the
// route with the `qrcode` lib and passed in.

import React from 'react'
import { Document, Page, View, Text, Image, StyleSheet, Font, TextInput, Checkbox } from '@react-pdf/renderer'
import type { SafetySite, SiteBoard } from './safety'
import { ENTITY_LABEL } from './safety'

// No hyphenation anywhere on the board - signage must not break words.
Font.registerHyphenationCallback(word => [word])

const MM = 2.8346457   // points per millimetre
const PAGE_W = 600 * MM
const PAGE_H = 900 * MM
const PAD = 18 * MM

// Palette pulled off the physical board.
const YELLOW = '#F2A900'
const RED = '#C8102E'
const BLACK = '#1A1A1A'
const WHITE = '#FFFFFF'

const s = StyleSheet.create({
  page: { backgroundColor: YELLOW, fontFamily: 'Helvetica', padding: PAD, flexDirection: 'column' },
  title: { fontSize: 128, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.02 },
  subtitle: { fontSize: 46, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', marginTop: 14 },
  body: { flexDirection: 'row', marginTop: 12 * MM, flexGrow: 1 },
  leftRail: { width: 150 * MM, marginRight: 12 * MM, flexDirection: 'column' },
  main: { flex: 1, flexDirection: 'column' },

  railHeading: { fontSize: 46, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.15 },
  qrBox: { backgroundColor: WHITE, borderWidth: 8, borderColor: RED, borderStyle: 'dashed', padding: 8 * MM, marginTop: 8 * MM, alignItems: 'center' },
  qr: { width: 116 * MM, height: 116 * MM },
  emgBlock: { backgroundColor: WHITE, marginTop: 12 * MM, padding: 8 * MM, alignItems: 'center' },
  emgHeader: { backgroundColor: RED, color: WHITE, fontSize: 46, fontFamily: 'Helvetica-Bold', paddingVertical: 8, paddingHorizontal: 30, marginBottom: 14 },
  emgNumber: { fontSize: 96, fontFamily: 'Helvetica-Bold', color: BLACK, lineHeight: 1.04 },
  emgMobile: { fontSize: 28, color: BLACK, marginBottom: 12 },
  emgServices: { fontSize: 38, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.35, borderTopWidth: 4, borderTopColor: BLACK, paddingTop: 14, alignSelf: 'stretch' },
  ppeBlock: { backgroundColor: WHITE, marginTop: 12 * MM, padding: 8 * MM },
  ppeHeader: { backgroundColor: RED, color: WHITE, fontSize: 34, fontFamily: 'Helvetica-Bold', textAlign: 'center', paddingVertical: 12, paddingHorizontal: 6, lineHeight: 1.25 },
  ppeList: { fontSize: 32, color: BLACK, lineHeight: 1.6, marginTop: 12 },
  danger: { backgroundColor: WHITE, borderWidth: 4, borderColor: BLACK, padding: 16, marginTop: 12 * MM },
  dangerWord: { backgroundColor: RED, color: WHITE, fontSize: 44, fontFamily: 'Helvetica-Bold', textAlign: 'center', paddingVertical: 8, borderRadius: 40, marginBottom: 12 },
  dangerText: { fontSize: 30, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.3 },
  brand: { marginTop: 10 * MM, alignItems: 'center' },
  brandName: { fontSize: 54, fontFamily: 'Helvetica-Bold', color: BLACK },
  brandSub: { fontSize: 24, color: BLACK, marginTop: 6, textAlign: 'center' },

  section: { backgroundColor: BLACK, padding: 6 },
  sectionHeader: { backgroundColor: RED, color: WHITE, fontSize: 40, fontFamily: 'Helvetica-Bold', paddingVertical: 10, paddingHorizontal: 16 },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  cell: { backgroundColor: WHITE, borderWidth: 2, borderColor: BLACK },
  cellLabel: { backgroundColor: BLACK, color: WHITE, fontSize: 24, fontFamily: 'Helvetica-Bold', paddingVertical: 7, paddingHorizontal: 10 },
  cellInput: { fontSize: 34, color: BLACK, margin: 8, height: 78 },
  cellInputTall: { fontSize: 34, color: BLACK, margin: 8, height: 96 },

  hazardsNote: { backgroundColor: WHITE, paddingVertical: 8, paddingHorizontal: 12 },
  hazardRow: { flexDirection: 'row', backgroundColor: WHITE, borderBottomWidth: 2, borderBottomColor: BLACK, alignItems: 'stretch', flexGrow: 1 },
  hazardTick: { width: 60, borderRightWidth: 2, borderRightColor: BLACK, alignItems: 'center', justifyContent: 'center' },
  hazardLabel: { flex: 5, fontSize: 27, fontFamily: 'Helvetica-Bold', color: BLACK, paddingVertical: 10, paddingHorizontal: 12, borderRightWidth: 2, borderRightColor: BLACK },
  hazardControl: { flex: 7, fontSize: 24, color: BLACK, paddingVertical: 10, paddingHorizontal: 12 },
  reviewRow: { backgroundColor: WHITE, paddingVertical: 10, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center' },
})

let fieldSeq = 0
function FillCell({ label, value, width, tall }: { label: string; value: string; width: string; tall?: boolean }) {
  return (
    <View style={[s.cell, { width }]}>
      <Text style={s.cellLabel}>{label}</Text>
      <TextInput
        name={`f${fieldSeq++}_${label.toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 40)}`}
        value={value || ''}
        style={tall ? s.cellInputTall : s.cellInput}
      />
    </View>
  )
}

export function SiteBoardPdf({ site, board, qrDataUrl }: { site: SafetySite; board: SiteBoard; qrDataUrl: string }) {
  fieldSeq = 0
  return (
    <Document title={`Site board - ${site.address}`}>
      <Page size={[PAGE_W, PAGE_H]} style={s.page}>
        <Text style={s.title}>NOTICE ABOUT BUILDING WORK</Text>
        <Text style={s.subtitle}>Everyone must sign in / out by scanning the QR code</Text>

        <View style={s.body}>
          {/* Left rail */}
          <View style={s.leftRail}>
            <Text style={s.railHeading}>SCAN TO{'\n'}SIGN IN / OUT</Text>
            <View style={s.qrBox}>
              {/* eslint-disable-next-line jsx-a11y/alt-text */}
              <Image src={qrDataUrl} style={s.qr} />
            </View>
            <View style={s.emgBlock}>
              <Text style={s.emgHeader}>EMERGENCY</Text>
              <Text style={s.emgNumber}>000</Text>
              <Text style={s.emgNumber}>112</Text>
              <Text style={s.emgMobile}>(Mobile)</Text>
              <Text style={s.emgServices}>POLICE{'\n'}FIRE{'\n'}AMBULANCE</Text>
            </View>
            <View style={s.ppeBlock}>
              <Text style={s.ppeHeader}>PPE MUST BE WORN ON-SITE WHEN REQUIRED</Text>
              <Text style={s.ppeList}>
                {'•'} Eye & hearing protection{'\n'}
                {'•'} Safety footwear{'\n'}
                {'•'} Respiratory protection{'\n'}
                {'•'} Hard hat / hi-vis
              </Text>
            </View>
            <View style={{ flexGrow: 1 }} />
            <View style={s.danger}>
              <Text style={s.dangerWord}>DANGER</Text>
              <Text style={s.dangerText}>NO ENTRY{'\n'}AUTHORISED PERSONNEL ONLY</Text>
            </View>
            <View style={s.brand}>
              <Text style={s.brandName}>{site.entity === 'lume' ? 'LUME POOLS' : 'FORMATION'}</Text>
              <Text style={s.brandSub}>{ENTITY_LABEL[site.entity]} {'·'} {site.shortRef}</Text>
            </View>
          </View>

          {/* Main column */}
          <View style={s.main}>
            {/* Site information */}
            <View style={s.section}>
              <Text style={s.sectionHeader}>Site Information</Text>
              <View style={s.grid}>
                <FillCell width="50%" tall label="Site Address" value={site.address} />
                <FillCell width="50%" tall label="Building Surveyors Name, Contact Number and Registration Number" value={board.buildingSurveyor} />
                <FillCell width="50%" label="Principal Contractor" value={board.principalContractor || ENTITY_LABEL[site.entity]} />
                <FillCell width="50%" label="Principal Contractor Number" value={board.principalContractorNumber} />
                <FillCell width="50%" label="Building Registration Number" value={board.buildingRegistrationNumber} />
                <FillCell width="50%" label="Building Permit Number / Date of Issue" value={board.buildingPermit} />
                <FillCell width="50%" label="Site Supervisor Name and Number" value={board.supervisorNameNumber} />
                <FillCell width="50%" label="H&S Manager Name and Number" value={board.hsManagerNameNumber} />
              </View>
            </View>

            {/* Emergency information */}
            <View style={[s.section, { marginTop: 8 * MM }]}>
              <Text style={s.sectionHeader}>Emergency Information</Text>
              <View style={s.grid}>
                <FillCell width="25%" label="Site First Aider" value={board.firstAider} />
                <FillCell width="25%" label="Contact Number" value={board.firstAidContact} />
                <FillCell width="25%" label="First Aid Location" value={board.firstAidLocation} />
                <FillCell width="25%" label="Fire Fighting Equipment Location" value={board.fireEquipmentLocation} />
                <FillCell width="33.33%" label="Site Emergency Signal" value={board.emergencySignal} />
                <FillCell width="33.33%" label="Site Assembly Area" value={board.assemblyArea} />
                <FillCell width="33.34%" label="Nearest Medical Centre" value={board.nearestMedical} />
              </View>
            </View>

            {/* Current site hazards - stretches to fill the remaining height */}
            <View style={[s.section, { marginTop: 8 * MM, flexGrow: 1, flexDirection: 'column' }]}>
              <Text style={s.sectionHeader}>Current Site Hazards</Text>
              <View style={s.hazardsNote}>
                <Text style={{ fontSize: 22, color: RED, fontFamily: 'Helvetica-Bold' }}>
                  Check the box if the hazard is present on-site
                </Text>
              </View>
              <View style={{ flexGrow: 1, flexDirection: 'column' }}>
                {board.hazards.map((h, i) => (
                  <View key={i} style={s.hazardRow}>
                    <View style={s.hazardTick}>
                      <Checkbox name={`hazard_${i}`} checked={h.checked} style={{ width: 34, height: 34 }} />
                    </View>
                    <Text style={s.hazardLabel}>{h.label}</Text>
                    <Text style={s.hazardControl}>{h.control}</Text>
                  </View>
                ))}
              </View>
              <View style={s.reviewRow}>
                <Text style={{ fontSize: 26, fontFamily: 'Helvetica-Bold', color: BLACK }}>Date Hazard Board Reviewed :  </Text>
                <TextInput name="hazards_reviewed_on" style={{ fontSize: 26, color: BLACK, width: 320, height: 40 }}
                  value={board.hazardsReviewedOn ? new Date(`${board.hazardsReviewedOn}T00:00:00`).toLocaleDateString('en-AU') : ''} />
              </View>
            </View>
          </View>
        </View>
      </Page>
    </Document>
  )
}
