// The printable 600x900mm site board ("Notice about building work") - the HazardCo board,
// rebuilt in-house. Rendered with @react-pdf/renderer at true print size so the print shop
// gets a 1:1 PDF: 600x900mm = [1700.79, 2551.18] points (1pt = 1/72", 1mm = 2.8346pt).
//
// Layout mirrors the physical board Chris photographed: black title band, left rail (QR
// sign-in block, EMERGENCY 000/112, PPE), right area (Site Information grid, Emergency
// Information, Current Site Hazards checklist), DANGER strip + brand footer.
//
// Server-only (imported by the board-pdf route). The QR png (data URL) is generated by the
// route with the `qrcode` lib and passed in.

import React from 'react'
import { Document, Page, View, Text, Image, StyleSheet } from '@react-pdf/renderer'
import type { SafetySite, SiteBoard } from './safety'
import { ENTITY_LABEL } from './safety'

const MM = 2.8346457   // points per millimetre
const PAGE_W = 600 * MM
const PAGE_H = 900 * MM

// Palette pulled off the physical board.
const YELLOW = '#F2A900'
const RED = '#C8102E'
const BLACK = '#1A1A1A'
const WHITE = '#FFFFFF'

const s = StyleSheet.create({
  page: { backgroundColor: YELLOW, fontFamily: 'Helvetica', padding: 24 * MM },
  title: { fontSize: 118, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center' },
  subtitle: { fontSize: 42, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', marginTop: 8 },
  body: { flexDirection: 'row', marginTop: 20 * MM },
  leftRail: { width: 130 * MM, marginRight: 12 * MM },
  main: { flex: 1 },
  railHeading: { fontSize: 40, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.15 },
  qrBox: { backgroundColor: WHITE, borderWidth: 6, borderColor: RED, borderStyle: 'dashed', padding: 10 * MM, marginTop: 8 * MM, alignItems: 'center' },
  qr: { width: 92 * MM, height: 92 * MM },
  emgBlock: { backgroundColor: WHITE, marginTop: 14 * MM, padding: 8 * MM, alignItems: 'center' },
  emgHeader: { backgroundColor: RED, color: WHITE, fontSize: 38, fontFamily: 'Helvetica-Bold', paddingVertical: 6, paddingHorizontal: 24, marginBottom: 10 },
  emgNumber: { fontSize: 72, fontFamily: 'Helvetica-Bold', color: BLACK, lineHeight: 1.05 },
  emgMobile: { fontSize: 24, color: BLACK, marginBottom: 8 },
  emgServices: { fontSize: 30, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.3, borderTopWidth: 3, borderTopColor: BLACK, paddingTop: 10, alignSelf: 'stretch' },
  ppeBlock: { backgroundColor: WHITE, marginTop: 14 * MM, padding: 8 * MM },
  ppeHeader: { backgroundColor: RED, color: WHITE, fontSize: 30, fontFamily: 'Helvetica-Bold', textAlign: 'center', paddingVertical: 8, lineHeight: 1.2 },
  ppeList: { fontSize: 26, color: BLACK, lineHeight: 1.5, marginTop: 10 },
  section: { backgroundColor: BLACK, padding: 5 },
  sectionHeader: { backgroundColor: RED, color: WHITE, fontSize: 34, fontFamily: 'Helvetica-Bold', paddingVertical: 8, paddingHorizontal: 14 },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  cell: { backgroundColor: WHITE, borderWidth: 2, borderColor: BLACK },
  cellLabel: { backgroundColor: BLACK, color: WHITE, fontSize: 20, fontFamily: 'Helvetica-Bold', paddingVertical: 4, paddingHorizontal: 8 },
  cellValue: { fontSize: 30, color: BLACK, padding: 10, minHeight: 60 },
  hazardRow: { flexDirection: 'row', backgroundColor: WHITE, borderBottomWidth: 1.5, borderBottomColor: BLACK },
  hazardTick: { width: 44, borderRightWidth: 1.5, borderRightColor: BLACK, alignItems: 'center', justifyContent: 'center' },
  tickBox: { width: 26, height: 26, borderWidth: 2.5, borderColor: BLACK, alignItems: 'center', justifyContent: 'center' },
  tick: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: BLACK, marginTop: -3 },
  hazardLabel: { flex: 5, fontSize: 22, color: BLACK, paddingVertical: 8, paddingHorizontal: 10, borderRightWidth: 1.5, borderRightColor: BLACK },
  hazardControl: { flex: 7, fontSize: 20, color: BLACK, paddingVertical: 8, paddingHorizontal: 10 },
  footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 * MM },
  danger: { backgroundColor: WHITE, borderWidth: 3, borderColor: BLACK, padding: 12, width: 150 * MM },
  dangerWord: { backgroundColor: RED, color: WHITE, fontSize: 34, fontFamily: 'Helvetica-Bold', textAlign: 'center', paddingVertical: 4, borderRadius: 30, marginBottom: 8 },
  dangerText: { fontSize: 24, fontFamily: 'Helvetica-Bold', color: BLACK, textAlign: 'center', lineHeight: 1.25 },
  brand: { alignItems: 'flex-end' },
  brandName: { fontSize: 52, fontFamily: 'Helvetica-Bold', color: BLACK },
  brandSub: { fontSize: 24, color: BLACK, marginTop: 4 },
})

function Cell({ label, value, width }: { label: string; value: string; width: string }) {
  return (
    <View style={[s.cell, { width }]}>
      <Text style={s.cellLabel}>{label}</Text>
      <Text style={s.cellValue}>{value || ' '}</Text>
    </View>
  )
}

export function SiteBoardPdf({ site, board, qrDataUrl }: { site: SafetySite; board: SiteBoard; qrDataUrl: string }) {
  const reviewed = board.hazardsReviewedOn
    ? new Date(`${board.hazardsReviewedOn}T00:00:00`).toLocaleDateString('en-AU')
    : '        /        /        '
  return (
    <Document title={`Site board - ${site.address}`}>
      <Page size={[PAGE_W, PAGE_H]} style={s.page}>
        <Text style={s.title}>NOTICE ABOUT BUILDING WORK</Text>
        <Text style={s.subtitle}>Everyone must sign in / out by scanning the QR code</Text>

        <View style={s.body}>
          {/* Left rail */}
          <View style={s.leftRail}>
            <Text style={s.railHeading}>SCAN TO{'\n'}SIGN IN / OUT</Text>
            <View style={s.qrBox}>
              {/* eslint-disable-next-line jsx-a11y/alt-text */}
              <Image src={qrDataUrl} style={s.qr} />
            </View>
            <View style={s.emgBlock}>
              <Text style={s.emgHeader}>EMERGENCY</Text>
              <Text style={s.emgNumber}>000</Text>
              <Text style={s.emgNumber}>112</Text>
              <Text style={s.emgMobile}>(Mobile)</Text>
              <Text style={s.emgServices}>POLICE{'\n'}FIRE{'\n'}AMBULANCE</Text>
            </View>
            <View style={s.ppeBlock}>
              <Text style={s.ppeHeader}>PPE MUST be worn on-site WHEN REQUIRED</Text>
              <Text style={s.ppeList}>
                {'•'} Eye & hearing protection{'\n'}
                {'•'} Safety footwear{'\n'}
                {'•'} Respiratory protection{'\n'}
                {'•'} Hard hat / hi-vis
              </Text>
            </View>
          </View>

          {/* Main column */}
          <View style={s.main}>
            {/* Site information */}
            <View style={s.section}>
              <Text style={s.sectionHeader}>Site Information</Text>
              <View style={s.grid}>
                <Cell width="50%" label="Site Address" value={site.address} />
                <Cell width="50%" label="Building Surveyors Name, Contact Number and Registration Number" value={board.buildingSurveyor} />
                <Cell width="50%" label="Principal Contractor" value={board.principalContractor || ENTITY_LABEL[site.entity]} />
                <Cell width="50%" label="Principal Contractor Number" value={board.principalContractorNumber} />
                <Cell width="50%" label="Building Registration Number" value={board.buildingRegistrationNumber} />
                <Cell width="50%" label="Building Permit Number / Date of Issue" value={board.buildingPermit} />
                <Cell width="50%" label="Site Supervisor Name and Number" value={board.supervisorNameNumber} />
                <Cell width="50%" label="H&S Manager Name and Number" value={board.hsManagerNameNumber} />
              </View>
            </View>

            {/* Emergency information */}
            <View style={[s.section, { marginTop: 8 * MM }]}>
              <Text style={s.sectionHeader}>Emergency Information</Text>
              <View style={s.grid}>
                <Cell width="25%" label="Site First Aider" value={board.firstAider} />
                <Cell width="25%" label="Contact Number" value={board.firstAidContact} />
                <Cell width="25%" label="First Aid Location" value={board.firstAidLocation} />
                <Cell width="25%" label="Fire Fighting Equipment Location" value={board.fireEquipmentLocation} />
                <Cell width="33.33%" label="Site Emergency Signal" value={board.emergencySignal} />
                <Cell width="33.33%" label="Site Assembly Area" value={board.assemblyArea} />
                <Cell width="33.34%" label="Nearest Medical Centre" value={board.nearestMedical} />
              </View>
            </View>

            {/* Current site hazards */}
            <View style={[s.section, { marginTop: 8 * MM }]}>
              <Text style={s.sectionHeader}>Current Site Hazards</Text>
              <View style={{ backgroundColor: WHITE, paddingVertical: 4, paddingHorizontal: 10 }}>
                <Text style={{ fontSize: 18, color: RED, fontFamily: 'Helvetica-Bold' }}>
                  Check [{'✓'}] if hazard is present on-site
                </Text>
              </View>
              {board.hazards.map((h, i) => (
                <View key={i} style={s.hazardRow}>
                  <View style={s.hazardTick}>
                    <View style={s.tickBox}>{h.checked ? <Text style={s.tick}>{'✓'}</Text> : null}</View>
                  </View>
                  <Text style={s.hazardLabel}>{h.label}</Text>
                  <Text style={s.hazardControl}>{h.control}</Text>
                </View>
              ))}
              <View style={{ backgroundColor: WHITE, paddingVertical: 8, paddingHorizontal: 10 }}>
                <Text style={{ fontSize: 20, fontFamily: 'Helvetica-Bold', color: BLACK }}>
                  Date Hazard Board Reviewed :  {reviewed}
                </Text>
              </View>
            </View>

            {/* Footer: danger + brand */}
            <View style={s.footer}>
              <View style={s.danger}>
                <Text style={s.dangerWord}>DANGER</Text>
                <Text style={s.dangerText}>NO ENTRY{'\n'}AUTHORISED PERSONNEL ONLY</Text>
              </View>
              <View style={s.brand}>
                <Text style={s.brandName}>{site.entity === 'lume' ? 'LUME POOLS' : 'FORMATION'}</Text>
                <Text style={s.brandSub}>{ENTITY_LABEL[site.entity]} {'·'} {site.shortRef}</Text>
              </View>
            </View>
          </View>
        </View>
      </Page>
    </Document>
  )
}
